export const SERVICE_PAGES = [
  {
    slug: 'consultoria-de-branding',
    title: 'Consultoria de branding para empresas | Arcaffo',
    description: 'Consultoria de branding para alinhar posicionamento, identidade, cultura e decisões de negócio. Conheça a abordagem da Arcaffo e solicite uma conversa.',
    name: 'Consultoria de branding',
    eyebrow: 'Estratégia de marca',
    h1: 'Consultoria de branding para transformar marca em direção',
    lead: 'A Arcaffo acompanha empresas que precisam organizar posicionamento, identidade, cultura e comunicação em torno de uma direção comum. O trabalho começa pelo negócio e chega à forma como a marca é percebida, vivida e escolhida.',
    symptoms: ['A comunicação muda a cada campanha, mas a percepção da empresa permanece igual.', 'A marca cresceu, porém a identidade e o discurso ainda representam uma fase anterior.', 'Liderança, equipe comercial e marketing explicam a empresa de maneiras diferentes.', 'Há investimento em divulgação, mas falta uma decisão clara sobre o que a marca deve significar.'],
    diagnosis: 'Consultoria de branding é um processo de diagnóstico e decisão. Ela investiga contexto, públicos, cultura, concorrência, proposta de valor e ambição do negócio para definir um posicionamento que possa orientar escolhas reais. O resultado não é apenas um documento: é um critério compartilhado para produto, experiência, comunicação, vendas e gestão.',
    approach: [
      ['Leitura do negócio', 'Entendemos história, modelo de negócio, momento da empresa, objetivos e tensões que motivaram a busca pela consultoria.'],
      ['Diagnóstico de marca', 'Analisamos discurso, identidade, pontos de contato, públicos, concorrência e coerência entre promessa e experiência.'],
      ['Direção estratégica', 'Definimos território, posicionamento, proposta de valor, narrativa e princípios que organizam as decisões da marca.'],
      ['Desdobramento', 'Transformamos a direção em prioridades para identidade, comunicação, cultura, marketing e presença comercial.'],
    ],
    deliverables: ['Diagnóstico de marca e contexto competitivo', 'Plataforma de marca e posicionamento', 'Proposta de valor e mensagens prioritárias', 'Diretrizes de identidade e comunicação', 'Plano de implementação com prioridades'],
    fit: 'É indicada para empresas em crescimento, reposicionamento, sucessão, expansão de portfólio ou perda de diferenciação. Também atende organizações que já investem em marketing, mas percebem que a execução não compensa a falta de uma direção central.',
    notFit: 'Se a necessidade é somente produzir uma peça, uma campanha isolada ou um logotipo sem revisão estratégica, a consultoria provavelmente não é o ponto de partida adequado.',
    projects: ['indreco', 'kassar', 'sacralita'],
    articles: ['consultoria-de-branding-o-que-e-como-funciona', 'o-que-inclui-um-projeto-de-branding', 'quanto-custa-um-projeto-de-branding-em-2026'],
    faq: [
      ['Qual a diferença entre consultoria de branding e agência de marketing?', 'A consultoria define a direção da marca e os critérios que orientam decisões. A agência de marketing normalmente planeja e executa ações de comunicação e aquisição. As duas frentes podem trabalhar juntas, desde que a execução responda a uma estratégia clara.'],
      ['A consultoria inclui identidade visual?', 'O escopo pode incluir criação ou redesign da identidade visual quando o diagnóstico mostra essa necessidade. Em outros casos, a identidade atual pode ser preservada e o foco fica no posicionamento, na narrativa ou na implementação.'],
      ['Quanto tempo dura?', 'O prazo depende do problema, do número de públicos envolvidos e dos desdobramentos contratados. A definição de escopo acontece depois de uma conversa de diagnóstico.'],
    ],
  },
  {
    slug: 'posicionamento-de-marca',
    title: 'Posicionamento de marca para empresas | Arcaffo',
    description: 'Posicionamento de marca para diferenciar sua empresa, organizar a narrativa e orientar marketing, vendas e experiência. Conheça o processo da Arcaffo.',
    name: 'Posicionamento de marca',
    eyebrow: 'Clareza competitiva',
    h1: 'Posicionamento de marca que orienta decisões e crescimento',
    lead: 'Posicionamento é a escolha consciente do lugar que uma marca pretende ocupar na mente e na vida de seus públicos. Ele deixa claro para quem a empresa existe, qual valor entrega, por que merece ser escolhida e quais caminhos não combinam com ela.',
    symptoms: ['A empresa disputa principalmente por preço.', 'O público não percebe diferença relevante entre a marca e os concorrentes.', 'A comunicação reúne muitos argumentos, mas nenhum se torna memorável.', 'Novos produtos e serviços surgem sem uma lógica que organize o portfólio.'],
    diagnosis: 'Um posicionamento consistente conecta verdade interna, relevância para o público e diferença competitiva. Ele não nasce de uma frase de efeito. Exige pesquisa, leitura do mercado e escolhas capazes de atravessar comunicação, produto, atendimento, cultura e experiência.',
    approach: [
      ['Contexto e ambição', 'Alinhamos objetivos do negócio, momento da empresa e visão de futuro da liderança.'],
      ['Públicos e mercado', 'Mapeamos expectativas, alternativas existentes, códigos da categoria e oportunidades de diferenciação.'],
      ['Tese de posicionamento', 'Construímos uma definição clara de público, território, valor, personalidade e razões para acreditar.'],
      ['Expressão e ativação', 'Traduzimos a tese em mensagens, prioridades de experiência e critérios para marketing e vendas.'],
    ],
    deliverables: ['Diagnóstico de percepção e concorrência', 'Território e tese de posicionamento', 'Proposta de valor', 'Narrativa e mensagens centrais', 'Princípios de ativação'],
    fit: 'O trabalho faz sentido quando a empresa amadureceu, entrou em uma nova categoria, ampliou a oferta, enfrenta comoditização ou percebe que sua reputação não acompanha a qualidade do que entrega.',
    notFit: 'Posicionamento não substitui qualidade operacional. Quando a promessa ainda não pode ser sustentada pela experiência, o primeiro passo é corrigir a entrega e alinhar expectativas.',
    projects: ['indreco', 'kassar', 'sacralita'],
    articles: ['o-poder-do-posicionamento-e-arquitetura-de-marca-em-mercados-competitivos', 'sinais-de-que-a-marca-nao-acompanha-o-crescimento-da-empresa', 'branding-para-empresas-b2b'],
    faq: [
      ['O que um projeto de posicionamento entrega?', 'Entrega uma direção estratégica: público prioritário, território, proposta de valor, diferenças relevantes, narrativa e critérios para colocar essa escolha em prática.'],
      ['Posicionamento é slogan?', 'Não. O slogan pode expressar uma parte do posicionamento, mas o posicionamento é uma decisão mais ampla que orienta comportamento, experiência, comunicação e oferta.'],
      ['É possível reposicionar sem trocar o logotipo?', 'Sim. A necessidade de redesign depende do diagnóstico. Algumas empresas precisam mudar a estratégia e a narrativa; outras também precisam atualizar o sistema visual para tornar a nova direção reconhecível.'],
    ],
  },
  {
    slug: 'identidade-visual',
    title: 'Identidade visual e redesign de marca | Arcaffo',
    description: 'Criação e redesign de identidade visual com fundamento estratégico: logotipo, sistema visual, aplicações e diretrizes para marcas reconhecíveis e coerentes.',
    name: 'Identidade visual',
    eyebrow: 'Estratégia que ganha forma',
    h1: 'Identidade visual para tornar a estratégia reconhecível',
    lead: 'Identidade visual é o sistema que torna uma marca identificável em diferentes contextos. Ela reúne logotipo, tipografia, cores, composição, imagens, grafismos e regras de aplicação para criar reconhecimento sem depender de repetir sempre a mesma peça.',
    symptoms: ['O logotipo existe, mas cada material parece pertencer a uma empresa diferente.', 'A identidade funciona em um formato e perde força em ambientes digitais, sinalização ou embalagem.', 'A estética ficou presa a uma fase anterior do negócio.', 'Fornecedores e equipes não têm critérios claros para produzir comunicação.'],
    diagnosis: 'Um bom sistema visual nasce de decisões estratégicas. Antes de desenhar, é preciso entender o que a marca representa, quem precisa reconhecê-la e em quais pontos de contato ela deve funcionar. A forma deixa de ser decoração e passa a comunicar personalidade, hierarquia e intenção.',
    approach: [
      ['Fundamento', 'Revisamos posicionamento, públicos, personalidade e requisitos práticos da marca.'],
      ['Conceito visual', 'Exploramos referências, códigos de categoria e caminhos capazes de expressar a estratégia sem recorrer a soluções genéricas.'],
      ['Sistema', 'Desenvolvemos logotipo, tipografia, cores, grafismos, direção de imagem e relações entre os elementos.'],
      ['Aplicação', 'Testamos o sistema nos pontos de contato relevantes e organizamos regras para manter consistência.'],
    ],
    deliverables: ['Logotipo e versões responsivas', 'Paleta cromática e tipografia', 'Elementos gráficos e direção de imagem', 'Aplicações prioritárias', 'Manual ou guia de identidade visual'],
    fit: 'É indicada para marcas novas com estratégia definida e para empresas consolidadas cuja expressão visual perdeu coerência, legibilidade ou capacidade de representar o negócio atual.',
    notFit: 'A identidade visual não corrige sozinha um posicionamento indefinido. Quando o problema central está na proposta de valor ou na direção do negócio, a estratégia precisa vir antes do desenho.',
    projects: ['cia-do-vidro', 'profive', 'la-parisienne'],
    articles: ['branding-identidade-visual-ou-logotipo-diferencas', 'rebranding-ou-redesign-como-saber-do-que-sua-empresa-precisa', 'o-que-inclui-um-projeto-de-branding'],
    faq: [
      ['Qual a diferença entre logotipo e identidade visual?', 'O logotipo é um dos elementos de identificação. A identidade visual é o sistema completo de formas, cores, tipografia, imagens e regras que cria unidade entre os pontos de contato.'],
      ['Quando fazer redesign?', 'Quando a identidade perdeu coerência, não funciona nos canais atuais, representa uma fase superada ou impede que o posicionamento seja percebido. Mudança estética sem motivo estratégico tende a envelhecer rápido.'],
      ['O projeto inclui manual da marca?', 'Sim, o formato do guia varia conforme a complexidade e os pontos de contato. Ele registra regras e exemplos para orientar equipe e fornecedores.'],
    ],
  },
  {
    slug: 'estrategia-de-marca',
    title: 'Estratégia de marca para empresas | Arcaffo',
    description: 'Estratégia de marca para alinhar proposta de valor, portfólio, narrativa, cultura e experiência às prioridades do negócio.',
    name: 'Estratégia de marca',
    eyebrow: 'Marca como critério',
    h1: 'Estratégia de marca para escolher com coerência',
    lead: 'Estratégia de marca organiza escolhas de longo prazo: onde competir, para quem gerar valor, o que sustentar como diferença e como transformar essa intenção em comportamento, experiência e comunicação.',
    symptoms: ['O portfólio cresceu sem uma arquitetura clara.', 'Marketing, comercial e operação seguem prioridades diferentes.', 'A marca depende demais da figura do fundador e pouco de um sistema compartilhado.', 'Projetos de comunicação começam por formato e canal, não por objetivo e significado.'],
    diagnosis: 'A estratégia cria um elo entre a ambição do negócio e a percepção construída ao longo do tempo. Ela define princípios suficientemente claros para orientar decisões e suficientemente flexíveis para acompanhar novos produtos, mercados e contextos.',
    approach: [
      ['Investigação', 'Reunimos dados, documentos e perspectivas de liderança, equipe, clientes e mercado.'],
      ['Síntese', 'Identificamos tensões, ativos, oportunidades e escolhas que a marca precisa assumir.'],
      ['Arquitetura', 'Organizamos proposta de valor, portfólio, públicos, personalidade, narrativa e relações entre marcas quando necessário.'],
      ['Governança', 'Definimos prioridades, responsáveis e critérios para que a estratégia seja usada no cotidiano.'],
    ],
    deliverables: ['Diagnóstico estratégico', 'Plataforma e princípios de marca', 'Arquitetura de portfólio quando aplicável', 'Narrativa e sistema de mensagens', 'Diretrizes de governança e ativação'],
    fit: 'É indicada para empresas com múltiplas ofertas, novos ciclos de crescimento, expansão geográfica, fusões, sucessão ou necessidade de alinhar marca e modelo de negócio.',
    notFit: 'Uma estratégia só cria valor quando a liderança está disposta a fazer escolhas e implementar consequências. Sem participação dos decisores, o material tende a virar apenas apresentação.',
    projects: ['sacralita', 'kassar', 'indreco'],
    articles: ['arquitetura-de-marca-como-organizar-produtos-servicos-e-submarcas', 'branding-para-empresas-b2b', 'consultoria-de-branding-o-que-e-como-funciona'],
    faq: [
      ['Estratégia de marca é o mesmo que planejamento de marketing?', 'Não. A estratégia de marca define significado, valor, diferenças e princípios duradouros. O planejamento de marketing transforma essa direção em objetivos, públicos, canais, campanhas e metas por período.'],
      ['O que é arquitetura de marca?', 'É a organização das relações entre empresa, produtos, serviços e submarcas. Ela ajuda públicos e equipes a entender o portfólio e evita sobreposição ou dispersão de reputação.'],
      ['Quem precisa participar do projeto?', 'A liderança responsável pelas decisões de negócio deve participar. Dependendo do escopo, também envolvemos equipes, clientes e outros públicos para ampliar a qualidade do diagnóstico.'],
    ],
  },
  {
    slug: 'consultoria-empresarial',
    title: 'Consultoria empresarial em Campo Grande | Arcaffo',
    description: 'Consultoria empresarial em Campo Grande para alinhar marca, modelo de negócio, marketing, vendas e cultura com acompanhamento estratégico.',
    name: 'Consultoria empresarial',
    eyebrow: 'Arcaffo Advisor',
    h1: 'Consultoria empresarial para transformar direção em rotina',
    lead: 'A Arcaffo Advisor acompanha empresários que precisam conectar estratégia e execução. O trabalho combina leitura do negócio, prioridades claras, encontros recorrentes e planos de ação para alinhar marca, marketing, vendas e cultura.',
    symptoms: ['A liderança está presa à operação e adia decisões estruturais.', 'A empresa cresce, mas processos, responsabilidades e comunicação não acompanham.', 'Marketing e vendas atuam sem uma direção compartilhada.', 'Há muitos projetos em andamento e pouca clareza sobre prioridade, responsável e sequência.'],
    diagnosis: 'Consultoria empresarial é um trabalho de orientação aplicado ao contexto real da empresa. Em vez de oferecer uma resposta genérica, organiza problemas, escolhas, responsáveis e cadência de acompanhamento. Na Arcaffo, marca e negócio são tratados como dimensões conectadas.',
    approach: [
      ['Diagnóstico', 'Lemos momento, objetivos, gargalos e indicadores disponíveis para definir o problema central.'],
      ['Prioridades', 'Escolhemos as frentes que exigem decisão e construímos um plano de ação viável.'],
      ['Acompanhamento', 'Encontros quinzenais com o estrategista mantêm decisões, responsáveis e próximos passos visíveis.'],
      ['Ajuste', 'A execução gera aprendizado. Revemos prioridades e orientamos novas decisões conforme a empresa avança.'],
    ],
    deliverables: ['Diagnóstico e definição de prioridades', 'Planos de ação táticos', 'Encontros quinzenais com estrategista', 'Suporte contínuo entre encontros', 'Acompanhamento de marca, marketing, vendas e cultura'],
    fit: 'É indicada para empresas estabelecidas, com equipe e operação em andamento, que precisam da participação ativa da liderança para estruturar um novo ciclo.',
    notFit: 'A assessoria não substitui a gestão da empresa nem executa todas as tarefas internas. Ela cria direção, acompanha decisões e articula especialistas quando o plano exige execução específica.',
    projects: ['indreco', 'iclay', 'rafael-a-obra'],
    articles: ['mapeando-a-jornada-do-cliente-como-atrair-reter-e-fidelizar', 'como-alinhar-a-cultura-organizacional-e-os-objetivos-dos-funciona-rios-nas-pmes', 'o-segredo-do-marketing-empresarial-como-alinhar-sua-verdade-a-conversa-o-de-vendas'],
    faq: [
      ['Qual a diferença entre projeto e assessoria?', 'Um projeto tem escopo e entrega definidos. A assessoria acompanha decisões ao longo do tempo, com ciclos de priorização, execução e ajuste.'],
      ['A consultoria atende fora de Campo Grande?', 'Sim. A Arcaffo está sediada em Campo Grande, MS, e pode atender empresas de outras regiões conforme o formato e o escopo definidos.'],
      ['A Arcaffo executa o plano?', 'A execução é combinada conforme a frente. Algumas atividades ficam com a equipe do cliente; outras podem envolver especialistas do ecossistema Arcaffo ou fornecedores já contratados pela empresa.'],
    ],
  },
  {
    slug: 'gestao-de-marketing',
    title: 'Gestão de marketing para empresas | Arcaffo',
    description: 'Gestão de marketing para alinhar estratégia, prioridades, canais, fornecedores e métricas ao posicionamento e aos objetivos da empresa.',
    name: 'Gestão de marketing',
    eyebrow: 'Direção antes do canal',
    h1: 'Gestão de marketing com estratégia, prioridade e acompanhamento',
    lead: 'Gestão de marketing organiza decisões antes de multiplicar ações. A Arcaffo ajuda a conectar posicionamento, objetivos comerciais, públicos, canais, responsáveis e métricas para que o investimento deixe de ser uma sequência de demandas isoladas.',
    symptoms: ['A empresa troca de agência ou fornecedor sem resolver a causa da frustração.', 'Há produção constante de conteúdo, mas pouca clareza sobre o papel de cada canal.', 'Marketing e vendas não compartilham definições de público, oferta e oportunidade.', 'Relatórios mostram alcance e cliques, mas não ajudam a decidir o próximo passo.'],
    diagnosis: 'A gestão começa pela pergunta de negócio, não pela plataforma. Ela define o que o marketing precisa mover, quais públicos importam, que mensagem sustenta a oferta e como acompanhar sinais de atenção, consideração e conversão.',
    approach: [
      ['Objetivo e diagnóstico', 'Revisamos posicionamento, oferta, jornada, canais, ativos, histórico e metas disponíveis.'],
      ['Plano tático', 'Organizamos públicos, mensagens, campanhas, conteúdo, responsabilidades, orçamento e cadência.'],
      ['Coordenação', 'Alinhamos equipe interna, agência e fornecedores para reduzir retrabalho e dispersão.'],
      ['Leitura e ajuste', 'Acompanhamos indicadores úteis para a decisão e revisamos hipóteses conforme os resultados.'],
    ],
    deliverables: ['Diagnóstico de marketing e comunicação', 'Objetivos, públicos e prioridades', 'Plano tático e calendário', 'Direção de campanhas e conteúdo', 'Rotina de acompanhamento e decisão'],
    fit: 'É indicada para empresas com operação e oferta validadas que já investem — ou estão prontas para investir — em marketing com participação da liderança e capacidade de executar o plano.',
    notFit: 'A gestão não transforma mídia em atalho para uma oferta fraca, uma experiência ruim ou uma marca sem clareza. Quando o problema está antes da divulgação, o diagnóstico redireciona a prioridade.',
    projects: ['iclay', 'la-parisienne', 'rafael-a-obra'],
    articles: ['o-segredo-do-marketing-empresarial-como-alinhar-sua-verdade-a-conversa-o-de-vendas', 'mapeando-a-jornada-do-cliente-como-atrair-reter-e-fidelizar', 'como-planejar-seus-anu-ncios-no-instagram'],
    faq: [
      ['Gestão de marketing inclui tráfego pago?', 'Pode incluir direção e acompanhamento de mídia, conforme o escopo. A decisão de investir em tráfego vem depois da revisão de oferta, público, mensagem, página e capacidade comercial.'],
      ['A Arcaffo substitui a equipe interna?', 'Não necessariamente. O trabalho pode orientar a equipe, coordenar fornecedores e definir prioridades. O desenho depende da estrutura já existente na empresa.'],
      ['Quais métricas são acompanhadas?', 'As métricas dependem do objetivo e da jornada. Em geral, combinamos indicadores de atenção, consideração, geração de oportunidades e qualidade comercial, evitando avaliar o trabalho por uma única métrica de vaidade.'],
    ],
  },
];

export const SERVICE_BY_SLUG = Object.fromEntries(SERVICE_PAGES.map(service => [service.slug, service]));
